# Site settings
title: 猫狗窝
header-img: "img/mimi.jpg"
tagline: "喵汪汪汪喵"  
description: "睡醒了 又是一条好汉"  
baseurl: ""
url: ""  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Ollie"
  email: lixinisme1115@126.com
  bio: "明朝即長路 惜取此時心"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: 
twitter_username:  
github_username: hunshiouren
facebook_username:  
weibo_username: 喵汪汪汪喵
zhihu_username: 李欣

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ollie"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Ollie
  disqus :
      short_name : Ollie

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation